"""empty message

Revision ID: 3b0c3215c58f
Revises: 176732fb2681
Create Date: 2025-11-05 13:59:12.193906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0c3215c58f'
down_revision = '176732fb2681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motpreferer', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('motpreferer')

    # ### end Alembic commands ###
