"""empty message

Revision ID: 442c30b5b163
Revises: 3b0c3215c58f
Create Date: 2025-11-05 15:07:06.577222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442c30b5b163'
down_revision = '3b0c3215c58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
